name: Sidekick Build

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      ASPNETCORE_ENVIRONMENT: Production
    steps:
    - name: Git - Checkout
      uses: actions/checkout@v2
    - name: .NET - Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: NuGet - Setup
      uses: NuGet/setup-nuget@v1.0.5
    - name: NuGet - Source
      uses: fabriciomurta/ensure-nuget-source@v1
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Tests
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
    - name: Tests - Unit Tests Report
      uses: dorny/test-reporter@v1.3.1
      with:
        name: Tests - Unit Tests
        path: '**/*.trx'
        reporter: dotnet-trx
    - name: Tests - Coverage Report
      uses: 5monkeys/cobertura-action@v8
      with:
        repo_token: ${{ github.token }}
        report_name: Tests - Coverage
        minimum_coverage: 0
        
